---
- name: Instalar pacotes essenciais
  hosts: webservers
  become: yes
  tasks:
    - name: Atualizar cache do apt
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalar pacotes básicos
      apt:
        name:
          - curl
          - wget
          - vim
          - htop
          - git
        state: present

    - name: Verificar se os pacotes foram instalados
      command: "{{ item }} --version"
      register: package_versions
      with_items:
        - curl
        - wget
        - vim
        - htop
        - git
      changed_when: false

    - name: Exibir versões dos pacotes
      debug:
        msg: "{{ item.cmd[0] }}: {{ item.stdout_lines[0] if item.stdout_lines else 'Instalado' }}"
      with_items: "{{ package_versions.results }}"
