---
- name: Instalacao e Configuracao do Servico FTP
  hosts: ftpserver
  become: yes
  vars:
    ftp_user: "ftpuser"
    ftp_password: "ftppass123"
    ftp_directory: "/home/ftpuser/ftp"

  tasks:
    - name: Atualizar cache do apt
      apt:
        update_cache: yes
      tags: update

    - name: Instalar vsftpd (servidor FTP)
      apt:
        name: vsftpd
        state: present
      tags: install

    - name: Criar usuario FTP
      user:
        name: "{{ ftp_user }}"
        password: "{{ ftp_password | password_hash('sha512') }}"
        home: "/home/{{ ftp_user }}"
        shell: /bin/bash
        create_home: yes
      tags: user

    - name: Criar diretorio FTP
      file:
        path: "{{ ftp_directory }}"
        state: directory
        owner: "{{ ftp_user }}"
        group: "{{ ftp_user }}"
        mode: '0755'
      tags: directory

    - name: Criar arquivo de teste no diretorio FTP
      copy:
        content: |
          Bem-vindo ao servidor FTP!
          Este e um arquivo de teste.
          Data de criacao: {{ ansible_date_time.date }}
        dest: "{{ ftp_directory }}/welcome.txt"
        owner: "{{ ftp_user }}"
        group: "{{ ftp_user }}"
        mode: '0644'
      tags: test-file

    - name: Configurar vsftpd
      copy:
        content: |
          # Configuracao basica do vsftpd
          listen=YES
          listen_port=21
          anonymous_enable=NO
          local_enable=YES
          write_enable=YES
          local_umask=022
          chroot_local_user=YES
          allow_writeable_chroot=YES
        dest: /etc/vsftpd.conf
        backup: yes
      notify: restart vsftpd
      tags: config

    - name: Iniciar e habilitar servico vsftpd
      shell: /etc/init.d/vsftpd start 


  handlers:
    - name: restart vsftpd
      shell: /etc/init.d/vsftpd restart 
